#!/bin/bash
# This file is part of Scanarium https://scanarium.com/ and licensed under the
# GNU Affero General Public License v3.0 (See LICENSE.md)
# SPDX-License-Identifier: AGPL-3.0-only

# To skip over this skript, set the environment variable to something non-empty
# E.g.:
#
#   export SKIP_PRE_COMMIT=y
#

set -e
set -o pipefail

sort_localizations() {
  maintenance/localization/sort.sh
  git add $(find localization -type f -name '*.json' ! -name 'localizations.json')
}

check_copyright_headers() {
  maintenance/copyright/check-headers.sh
}

pre_commit() {
  sort_localizations
  check_copyright_headers
}

if [ -z "$SKIP_PRE_COMMIT" ]
then
    if ! pre_commit
    then
        echo "Found $WARNINGS warnings. Aborting. Set SKIP_PRE_COMMIT to a non-empty value to skip tests" >&2
        exit 1
    fi
fi
